"""add metadata to findings

Revision ID: 150211713e2b
Revises: 20260202_0230_001
Create Date: 2026-02-02 14:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '150211713e2b'
down_revision = '20260202_0230_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('findings', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('findings', 'metadata')
    # ### end Alembic commands ###
